# application-dev.yml

spring:
  # 개발용 로컬 DB 정보 (실제 프로젝트의 로컬 DB 설정에 맞게 수정)
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ${DB_USER}
    password: ${DB_PASS}

  # JPA/Hibernate 설정 (개발 환경에서는 스키마 자동 생성 기능 활용 가능)
  jpa:
    hibernate:
      ddl-auto: validate # 또는 create (매번 스키마를 새로 생성)
    show-sql: true

# JWT 비밀키 등 민감 정보는 환경 변수로 받는 것이 좋습니다.
jwt:
  secret: ${JWT_SECRET_KEY}
  expires-in: ${JWT_EXPIRES_IN}
